### ISSUE TITLE
Terms/data definitions as web concepts?

### ISSUE THREAD

**Issue by pgroth** [dret/sedola#18]
Would something like 
http://www.w3.org/TR/prov-dm/
be appropriate for web concepts?

**Comment by dret** [comment]
On 2016-07-23 23:54, Paul Groth wrote:

> Would something like
> http://www.w3.org/TR/prov-dm/
> be appropriate for web concepts?

thanks for the feedback. my thinking is that web concepts should be 
strictly about things that are visible at the web level. PROV-DM and 
other RDF vocabularies are not visible at the web level. they are not 
even visible as a media type (in which case they could be added to 
http://webconcepts.info/concepts/media-types). they become visible at 
the semantic web level when there's RDF data (encoded in one of the RDF 
media types) and within that data the PROV-DM vocabulary may be used.

if we started collecting any vocabulary based on any media type that 
allows the usage of vocabularies (next to RDF at the very least you 
would have to consider XML and JSON and probably many more), that would 
be a very very long list. i think it makes more sense to try to be more 
selective and really only include what is visible on the web level.

**Comment by dret** [comment]
closing this for now; please re-open if further discussion is required.
