### ISSUE TITLE
Add JWT as access token type

### ISSUE THREAD

**Issue by nynymike** [dret/sedola#31]
In the page [Oauth Access Token Types](http://webconcepts.info/concepts/oauth-access-token-types) Bearer and MAC are listed, but I think JWT is missing.  [RFC 7519](https://tools.ietf.org/html/rfc7519#section-10.2.1)  specifies it.

```
This section registers the value "token-type:jwt" in the IANA "OAuth
   URI" registry established by "An IETF URN Sub-Namespace for OAuth"
   [RFC6755], which can be used to indicate that the content is a JWT.

   o  URN: urn:ietf:params:oauth:token-type:jwt
   o  Common Name: JSON Web Token (JWT) Token Type
   o  Change Controller: IESG
   o  Specification Document(s): RFC 7519
```

**Comment by nynymike** [comment]
I guess I'm wrong about this... a JWT is still a bearer token (just like a SAML assertion can be a bearer token). I'm going to post to the OAuth mailing list to see why they don't want this as a token type. It seems like it would be descriptive...

**Comment by dret** [comment]
On 2016-11-12 17:50, Mike Schwartz wrote:

> I guess I'm wrong about this... a JWT is still a bearer token (just like
> a SAML assertion can be a bearer token). I'm going to post to the OAuth
> mailing list to see why they don't want this as a token type. It seems
> like it would be descriptive...

seems like there's nothing to do for me after all. but thanks to 
pointing to that MAC draft, and if you find anything else, definitely 
let me know. thanks!
