### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by nynymike** [dret/sedola#32]
I can't find the license for this repository. Can you add one?

**Comment by dret** [comment]
On 2016-11-12 15:40, Mike Schwartz wrote:

> I can't find the license for this repository. Can you add one?

i should definitely do that, thanks for the suggestion!

**Comment by dret** [comment]
if this addresses the issue, please close it. thanks for the suggestion!

**Comment by dret** [comment]
assuming that this was good enough for @nynymike, and closing the issue (feel free to reopen if it wasn't).
