### ISSUE TITLE
Include spec id in concepts.json

### ISSUE THREAD

**Issue by tpluscode** [dret/sedola#35]
I'd like to include the spec signature with each concept in `concepts.json` (see pmhsfelix/slack-web-concept#6) so that it's not necessary to fetch and process `specs.json` every time. Ofc it would be possible to cache it but its structure isn't too friendly for finding the right spec anyway.

I would add a simple key/value to each spec in the format `"{organization} {series} {spec}"` (not sure I'm getting the naming right, so don't bash me). For example basic authentication details would become

```
{
  "description": "[...]",
  "documentation": "http://tools.ietf.org/html/rfc7617#section-2",
  "specification": "http://webconcepts.info/specs/IETF/RFC/7617",
  "specification-signature": "IETF RFC 7617"
}
```

I don't particularly like the `specification-signature`. Any better name?

What do you think?

**Comment by dret** [comment]
the current complete JSON structure as documented at http://webconcepts.info/JSON looks like this:

```json
{ "value": "GET",
  "concept": "http://webconcepts.info/concepts/http-method/",
  "id": "http://webconcepts.info/concepts/http-method/GET",
  "details": [
  { "description": "The GET method ...",
    "documentation": "http://tools.ietf.org/html/rfc7231#section-4.3.1",
    "specification": "http://webconcepts.info/specs/IETF/RFC/7231" }]}
```

looking at http://webconcepts.info/specs/specs.json what you called `specification-signature` is simply called `name` over there. i am not saying that `name` is a great name (;-), but i think it would be good to stay consistent.

however, the `name` for RFC 7231 is currently appearing as `"RFC 7231"` (no IETF). is that good enough, or maybe all the names should include the organization names anyway?

**Comment by tpluscode** [comment]
Sure, it's enough. People rarely refer to the organization anyways when talking about those specifications, don't they? 

I somehow missed `name`. I was looking at the complete path which you would get by concatenating the keys in `specs.json`. So, yes let's just got with that name and call it `specification-name`?

**Comment by dret** [comment]
the new member `spec-name` is implemented and documented. please close the issue if it works for you.

**Comment by tpluscode** [comment]
Works great. Thanks.
