### ISSUE TITLE
spec.json should identify concepts and concept values by URI

### ISSUE THREAD

**Issue by dret** [dret/sedola#36]
currently `spec.json` "identifies" concepts and values by string value only:

```json
{"ietf-httpbis-encryption-encoding": {
  "id": "http://webconcepts.info/specs/IETF/I-D/ietf-httpbis-encryption-encoding",
  "title": "Encrypted Content-Encoding for HTTP",
  "name": "Internet Draft ietf-httpbis-encryption-encoding",
  "URI": "urn:ietf:id:ietf-httpbis-encryption-encoding",
  "URL": "http://tools.ietf.org/html/draft-ietf-httpbis-encryption-encoding",
  "abstract": "This memo introduces a content coding for HTTP that allows message payloads to be encrypted.",
  "concepts": [
    {"http-content-coding": "aesgcm"},
    {"http-header": "Crypto-Key"},
    {"http-header": "Encryption"}]}}
```

this seems wrong because both concept and concept value should be identified by their ID (their URIs) as documented at http://webconcepts.info/JSON. i am inclined to just fix this, but wanted to see if anybody is using these values, and what they think about switching from plain strings to proper URIs.

**Comment by dret** [comment]
pinging @kinlane @arno-di-loreto @pmhsfelix @mitraman because you might be using this?

**Comment by arno-di-loreto** [comment]
I'm not using webconcepts yet (on my Christmas holidays todo list! ), so no problem for me.

**Comment by dret** [comment]
this issue is related to #24 which is about how to identify concepts (and values).

**Comment by dret** [comment]
On 2016-12-21 12:39, Arnaud Lauret wrote:
> I'm not using webconcepts yet (on my Christmas holidays todo list! ), so
> no problem for me.

happy holidays, and if there's any wish you have for web concepts, this 
is the time of the year to get them fulfilled!

**Comment by dret** [comment]
https://github.com/dret/webconcepts/commit/ffb2afcad5872748bbff86a671b5d581111fab10 should fix this.
