### ISSUE TITLE
New I-D: draft-ietf-httpbis-digest-headers

### ISSUE THREAD

**Issue by ioggstream** [dret/sedola#53]
## I wish

To reference https://github.com/httpwg/http-extensions/blob/master/draft-ietf-httpbis-digest-headers.md in your list of web-concepts.

## This spec

Will obsolete RFC 3230, which defines `Digest` and `Want-Digest`.

**Comment by dret** [comment]
On 2019-07-31 02:53, Roberto Polli wrote:
> To reference 
> https://github.com/httpwg/http-extensions/blob/master/draft-ietf-httpbis-digest-headers.md 
> in your list of web-concepts.
> Will obsolete RFC 3230, which defines |Digest| and |Want-Digest|.

i could add it, but it seems that from the definition point of view, 
those two headers are still defined by RFC 3230, right? if that's the 
case, it may make sense to wait until the RFC is obsoleted? or do you 
think it would make sense to reference the I-D already?

**Comment by ioggstream** [comment]
> those two headers are still defined by RFC 3230, 
Yes, but their definition is inconsistent with RFC723x because 
of the `entity -> representation` changes.

>  do you think it would make sense to reference the I-D already?
That depends on the web-concepts policy :)

While I hope that I-D to go RFC by 2020,
it's important that people using RFC3230 knows that it could become obsoleted and get in touch with us.

Always thanks for your time, R.

**Comment by dret** [comment]
On 2019-08-02 08:59, Roberto Polli wrote:
> While I hope that I-D to go RFC by 2020,
> it's important that people using RFC3230 knows that it could become 
> obsoleted and get in touch with us.

ok, i have added the draft. 
http://webconcepts.info/specs/IETF/I-D/ietf-httpbis-digest-headers is 
where you can find it, and it lists the two header fields as requested.

**Comment by ioggstream** [comment]
Thanks Erik! :rocket:
